# Generated by Django 3.1.4 on 2020-12-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20201224_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(default='Article-snippet', max_length=300),
        ),
    ]
